# Generated by Django 5.1.5 on 2025-01-26 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_user_id_alter_user_last_login_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='file_path',
        ),
        migrations.AddField(
            model_name='file',
            name='file_url',
            field=models.URLField(default='/#'),
            preserve_default=False,
        ),
    ]
