# Generated by Django 5.1.5 on 2025-01-28 19:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_file_file_path_file_file_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryFileLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('expiration_time', models.DateTimeField()),
                ('shared_with_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.file')),
            ],
        ),
    ]
