# Generated by Django 5.1.5 on 2025-01-28 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_temporaryfilelink'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporaryfilelink',
            name='generated_by',
            field=models.CharField(default='_id_', max_length=50),
        ),
    ]
