# Generated by Django 5.1.5 on 2025-01-28 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_rename_file_temporaryfilelink_file_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporaryfilelink',
            name='file_name',
            field=models.CharField(max_length=255),
        ),
    ]
