# Generated by Django 5.1.5 on 2025-01-26 12:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 26, 12, 37, 34, 734961, tzinfo=datetime.timezone.utc)),
        ),
    ]
